### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [tohyung85/starquotes#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tohyung85** [comment]
Thanks for advice Billy! Turns out all that was required was  a simple viewport meta tag in the header of the application.html.erb file. I included the following between the header tags:
`<meta name="viewport" content="initial-scale=1">`

As it turns out once i included the meta tag, noticed some of the alignments in my header and footer went off and so i made some minor tweaks and added the following to make sure it works well on mobile:
`@media (max-width: 375px) {`
`.links {`
`font-size: 20px;`
`}`

`.footer_comment {`
`font-size: 11px;`
`}`
`}`

As a side note, you got me curious when you mentioned the following in your code review email to me: 
"Getting page specific CSS is a bit tricky though, and to do it in a clean way from a CSS file (rather than hardcoding things), can involve setting specific classes based on the controller / action. "

Would you mind providing me with some references and examples which i can refer to? I somehow feel that understanding it would make me organized in my code and make me a better programmer! : )

Thanks again for the tip on the meta tags. I also learnt that I should always check how the website looks on my phone itself to be sure! (I have been testing by just reducing the size of my web browser)

**Comment by BillyMassey** [comment]
We’ll dive into some more advanced CSS topics like media queries, etc. in the third application you build out (the Flixter application), so I wouldn’t worry about getting it right now.  For the time being, I’d suggest continuing through the lessons.  

Feel free to ask your mentor about it in your upcoming mentor session if you’re looking for something to pair program on, but we’ll work with more advanced CSS later in the course.
